all:
  hosts:
    node-0:
      ansible_host: 158.160.38.118
      ansible_user: ubuntu
    node-1:
      ansible_host: 158.160.73.33
      ansible_user: ubuntu
    node-2:
      ansible_host: 158.160.131.224
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        node-0:
    kube_node:
      hosts:
        node-1:
        node-2:
    etcd:
      hosts:
        node-0:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
